[package]
name = "freya-css"
version = "0.1.0"
edition = "2021"
description = "CSS styling support for Freya UI framework, powered by cssengine."
license = "MIT OR Apache-2.0"
repository = "https://github.com/SergioRibera/cssengine"
homepage = "https://github.com/SergioRibera/cssengine"
keywords = ["css", "freya", "gui", "styling"]
categories = ["gui"]

[dependencies]
cssengine = { path = "../..", default-features = false }
freya-core = "0.4.0-rc.18"
torin = "0.4.0-rc.18"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
notify = "6"
